// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestUser struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestUser) Reset()         { *m = RequestUser{} }
func (m *RequestUser) String() string { return proto.CompactTextString(m) }
func (*RequestUser) ProtoMessage()    {}
func (*RequestUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}

func (m *RequestUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestUser.Unmarshal(m, b)
}
func (m *RequestUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestUser.Marshal(b, m, deterministic)
}
func (m *RequestUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestUser.Merge(m, src)
}
func (m *RequestUser) XXX_Size() int {
	return xxx_messageInfo_RequestUser.Size(m)
}
func (m *RequestUser) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestUser.DiscardUnknown(m)
}

var xxx_messageInfo_RequestUser proto.InternalMessageInfo

func (m *RequestUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RequestUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Uuid struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Uuid) Reset()         { *m = Uuid{} }
func (m *Uuid) String() string { return proto.CompactTextString(m) }
func (*Uuid) ProtoMessage()    {}
func (*Uuid) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{1}
}

func (m *Uuid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Uuid.Unmarshal(m, b)
}
func (m *Uuid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Uuid.Marshal(b, m, deterministic)
}
func (m *Uuid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Uuid.Merge(m, src)
}
func (m *Uuid) XXX_Size() int {
	return xxx_messageInfo_Uuid.Size(m)
}
func (m *Uuid) XXX_DiscardUnknown() {
	xxx_messageInfo_Uuid.DiscardUnknown(m)
}

var xxx_messageInfo_Uuid proto.InternalMessageInfo

func (m *Uuid) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type User struct {
	Uuid                 *Uuid    `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUuid() *Uuid {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UsersList struct {
	UserList             []*User  `protobuf:"bytes,1,rep,name=UserList,proto3" json:"UserList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersList) Reset()         { *m = UsersList{} }
func (m *UsersList) String() string { return proto.CompactTextString(m) }
func (*UsersList) ProtoMessage()    {}
func (*UsersList) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{3}
}

func (m *UsersList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersList.Unmarshal(m, b)
}
func (m *UsersList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersList.Marshal(b, m, deterministic)
}
func (m *UsersList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersList.Merge(m, src)
}
func (m *UsersList) XXX_Size() int {
	return xxx_messageInfo_UsersList.Size(m)
}
func (m *UsersList) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersList.DiscardUnknown(m)
}

var xxx_messageInfo_UsersList proto.InternalMessageInfo

func (m *UsersList) GetUserList() []*User {
	if m != nil {
		return m.UserList
	}
	return nil
}

type Null struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Null) Reset()         { *m = Null{} }
func (m *Null) String() string { return proto.CompactTextString(m) }
func (*Null) ProtoMessage()    {}
func (*Null) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{4}
}

func (m *Null) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Null.Unmarshal(m, b)
}
func (m *Null) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Null.Marshal(b, m, deterministic)
}
func (m *Null) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Null.Merge(m, src)
}
func (m *Null) XXX_Size() int {
	return xxx_messageInfo_Null.Size(m)
}
func (m *Null) XXX_DiscardUnknown() {
	xxx_messageInfo_Null.DiscardUnknown(m)
}

var xxx_messageInfo_Null proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RequestUser)(nil), "RequestUser")
	proto.RegisterType((*Uuid)(nil), "Uuid")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*UsersList)(nil), "UsersList")
	proto.RegisterType((*Null)(nil), "null")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_3eaf2c85e69e9ea4) }

var fileDescriptor_3eaf2c85e69e9ea4 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x6d, 0xda, 0xa4, 0xd0, 0x4b, 0x58, 0x4e, 0x0c, 0xc1, 0x0b, 0xc5, 0x2c, 0x4c, 0x1e, 0xca,
	0x0f, 0x40, 0x80, 0x2a, 0x16, 0xa6, 0x54, 0x5d, 0xd8, 0x42, 0x7b, 0x20, 0x4b, 0x4e, 0x02, 0xfe,
	0x40, 0xfc, 0x7c, 0xe4, 0x33, 0x44, 0x59, 0x98, 0xde, 0x3d, 0xdf, 0xbd, 0xf7, 0xce, 0x07, 0xd5,
	0x61, 0xe8, 0xdf, 0xf4, 0xbb, 0xfa, 0xb0, 0x83, 0x1f, 0xe4, 0x1d, 0x94, 0x0d, 0x7d, 0x06, 0x72,
	0x7e, 0xef, 0xc8, 0xa2, 0x80, 0xd3, 0x88, 0x7d, 0xdb, 0x51, 0x9d, 0xad, 0xb3, 0x9b, 0x55, 0x33,
	0x72, 0x3c, 0x87, 0x62, 0xdb, 0xb5, 0xda, 0xd4, 0x73, 0x6e, 0x24, 0x22, 0x05, 0xe4, 0xfb, 0xa0,
	0x8f, 0x88, 0x90, 0x87, 0xa0, 0x8f, 0xbf, 0x2a, 0xae, 0xe5, 0x0e, 0x72, 0x76, 0xbd, 0x48, 0x33,
	0xdc, 0x2b, 0x37, 0x85, 0x8a, 0xa4, 0x49, 0xb2, 0x69, 0xe0, 0xfc, 0xbf, 0xc0, 0xc5, 0x34, 0x50,
	0xc1, 0x2a, 0x4e, 0xb8, 0x67, 0xed, 0x3c, 0x5e, 0x25, 0x79, 0xac, 0xeb, 0x6c, 0xbd, 0x48, 0xee,
	0x8e, 0x6c, 0x33, 0x3e, 0xcb, 0x25, 0xe4, 0x7d, 0x30, 0x66, 0xf3, 0x0d, 0x15, 0xeb, 0x76, 0x64,
	0xbf, 0xf4, 0x81, 0xf0, 0x1a, 0xe0, 0xd1, 0x52, 0xeb, 0x89, 0x57, 0xac, 0xd4, 0xe4, 0x0c, 0x22,
	0x99, 0xc8, 0x19, 0x4a, 0x28, 0x9f, 0xc8, 0xdf, 0x1b, 0xc3, 0x52, 0x2c, 0x54, 0xb4, 0x12, 0xa0,
	0xc6, 0x0d, 0xe4, 0x0c, 0x2f, 0xe1, 0x6c, 0x6b, 0x74, 0xa7, 0xfb, 0x3f, 0xaf, 0xf4, 0x41, 0x91,
	0x40, 0xce, 0x1e, 0x4e, 0x5e, 0x0a, 0x3e, 0xf6, 0xeb, 0x92, 0xe1, 0xf6, 0x27, 0x00, 0x00, 0xff,
	0xff, 0x08, 0x1f, 0x4e, 0x4a, 0x83, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersServiceClient is the client API for UsersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersServiceClient interface {
	CreateUser(ctx context.Context, in *RequestUser, opts ...grpc.CallOption) (*User, error)
	GetAllUsers(ctx context.Context, in *Null, opts ...grpc.CallOption) (*UsersList, error)
	EliminateUser(ctx context.Context, in *Uuid, opts ...grpc.CallOption) (*Uuid, error)
}

type usersServiceClient struct {
	cc *grpc.ClientConn
}

func NewUsersServiceClient(cc *grpc.ClientConn) UsersServiceClient {
	return &usersServiceClient{cc}
}

func (c *usersServiceClient) CreateUser(ctx context.Context, in *RequestUser, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/UsersService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetAllUsers(ctx context.Context, in *Null, opts ...grpc.CallOption) (*UsersList, error) {
	out := new(UsersList)
	err := c.cc.Invoke(ctx, "/UsersService/GetAllUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) EliminateUser(ctx context.Context, in *Uuid, opts ...grpc.CallOption) (*Uuid, error) {
	out := new(Uuid)
	err := c.cc.Invoke(ctx, "/UsersService/EliminateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServiceServer is the server API for UsersService service.
type UsersServiceServer interface {
	CreateUser(context.Context, *RequestUser) (*User, error)
	GetAllUsers(context.Context, *Null) (*UsersList, error)
	EliminateUser(context.Context, *Uuid) (*Uuid, error)
}

// UnimplementedUsersServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUsersServiceServer struct {
}

func (*UnimplementedUsersServiceServer) CreateUser(ctx context.Context, req *RequestUser) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUsersServiceServer) GetAllUsers(ctx context.Context, req *Null) (*UsersList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllUsers not implemented")
}
func (*UnimplementedUsersServiceServer) EliminateUser(ctx context.Context, req *Uuid) (*Uuid, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EliminateUser not implemented")
}

func RegisterUsersServiceServer(s *grpc.Server, srv UsersServiceServer) {
	s.RegisterService(&_UsersService_serviceDesc, srv)
}

func _UsersService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UsersService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).CreateUser(ctx, req.(*RequestUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetAllUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Null)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetAllUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UsersService/GetAllUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetAllUsers(ctx, req.(*Null))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_EliminateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Uuid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).EliminateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UsersService/EliminateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).EliminateUser(ctx, req.(*Uuid))
	}
	return interceptor(ctx, in, info, handler)
}

var _UsersService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UsersService",
	HandlerType: (*UsersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UsersService_CreateUser_Handler,
		},
		{
			MethodName: "GetAllUsers",
			Handler:    _UsersService_GetAllUsers_Handler,
		},
		{
			MethodName: "EliminateUser",
			Handler:    _UsersService_EliminateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config.proto",
}
